export const db = [
  {
    id: 1,
    name: "Alice Svensson",
    email: "alice.svensson@example.com",
    class: "1A",
  },
  {
    id: 2,
    name: "Bob Karlsson",
    email: "bob.karlsson@example.com",
    class: "1A",
  },
  {
    id: 3,
    name: "Cecilia Eriksson",
    email: "cecilia.eriksson@example.com",
    class: "1A",
  },
  {
    id: 4,
    name: "David Larsson",
    email: "david.larsson@example.com",
    class: "1A",
  },
  {
    id: 5,
    name: "Elin Johansson",
    email: "elin.johansson@example.com",
    class: "1A",
  },
  {
    id: 6,
    name: "Felix Andersson",
    email: "felix.andersson@example.com",
    class: "1A",
  },
  {
    id: 7,
    name: "Greta Lundqvist",
    email: "greta.lundqvist@example.com",
    class: "1A",
  },
  {
    id: 8,
    name: "Hugo Berg",
    email: "hugo.berg@example.com",
    class: "1A",
  },
  {
    id: 9,
    name: "Isabella Nilsson",
    email: "isabella.nilsson@example.com",
    class: "1A",
  },
  {
    id: 10,
    name: "Jakob Persson",
    email: "jakob.persson@example.com",
    class: "1A",
  },
  {
    id: 11,
    name: "Klara Olsson",
    email: "klara.olsson@example.com",
    class: "2A",
  },
  {
    id: 12,
    name: "Leo Jonsson",
    email: "leo.jonsson@example.com",
    class: "2A",
  },
  {
    id: 13,
    name: "Matilda Holm",
    email: "matilda.holm@example.com",
    class: "2A",
  },
  {
    id: 14,
    name: "Noah Lindgren",
    email: "noah.lindgren@example.com",
    class: "2A",
  },
  {
    id: 15,
    name: "Olivia Sandström",
    email: "olivia.sandstrom@example.com",
    class: "2A",
  },
  {
    id: 16,
    name: "Pontus Ek",
    email: "pontus.ek@example.com",
    class: "2A",
  },
  {
    id: 17,
    name: "Quinn Forsberg",
    email: "quinn.forsberg@example.com",
    class: "2A",
  },
  {
    id: 18,
    name: "Rasmus Engström",
    email: "rasmus.engstrom@example.com",
    class: "2A",
  },
  {
    id: 19,
    name: "Sofia Björk",
    email: "sofia.bjork@example.com",
    class: "2A",
  },
  {
    id: 20,
    name: "Tim Westerberg",
    email: "tim.westerberg@example.com",
    class: "2A",
  },
];
